### ISSUE TITLE
Cannot install from PyPI on Python 3.11

### ISSUE THREAD

**Issue by jcbjoe** [M-o-a-T/asyncari#10]
Hi,

I cant seem to get the package to install. Its the old package in my requirements.txt.

Im running a M1 mac and im using the latest version of asyncari (0.10.16). The error im getting seems to be related to the "asks" package. Its complaining that h11 doesn't exist. However you can see it being installed in the log below.

```
pip install -r requirements.txt
Collecting asyncari==0.10.16 (from -r requirements.txt (line 2))
  Using cached asyncari-0.10.16-py3-none-any.whl.metadata (1.3 kB)
Collecting anyio>=4 (from asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached anyio-4.4.0-py3-none-any.whl.metadata (4.6 kB)
Collecting asks>=2.2 (from asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached asks-3.0.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... done
Collecting asyncswagger11 (from asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached asyncswagger11-0.12.4-py3-none-any.whl.metadata (5.8 kB)
Collecting asyncwebsockets (from asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached asyncwebsockets-0.9.4-py3-none-any.whl.metadata (1.5 kB)
Collecting attrs>=18 (from asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting idna>=2.8 (from anyio>=4->asyncari==0.10.16->-r requirements.txt (line 2))
  Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting sniffio>=1.1 (from anyio>=4->asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11 (from asks>=2.2->asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting async_generator (from asks>=2.2->asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached async_generator-1.10-py3-none-any.whl.metadata (4.9 kB)
INFO: pip is looking at multiple versions of asks to determine which version is compatible with other requirements. This could take a while.
Collecting asks>=2.2 (from asyncari==0.10.16->-r requirements.txt (line 2))
  Using cached asks-2.4.12.tar.gz (23 kB)
  Preparing metadata (setup.py) ... done
  Using cached asks-2.4.10.tar.gz (22 kB)
  Preparing metadata (setup.py) ... done
  Using cached asks-2.4.9.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/7f/56kg8qsn2cz0_sbtrcvn3j5c0000gn/T/pip-install-s_mpy7ne/asks_3499819a1d8a4566ab2f2ae1aa767ff6/setup.py", line 5, in <module>
          from asks import __version__ as version
        File "/private/var/folders/7f/56kg8qsn2cz0_sbtrcvn3j5c0000gn/T/pip-install-s_mpy7ne/asks_3499819a1d8a4566ab2f2ae1aa767ff6/asks/__init__.py", line 7, in <module>
          from .base_funcs import *
        File "/private/var/folders/7f/56kg8qsn2cz0_sbtrcvn3j5c0000gn/T/pip-install-s_mpy7ne/asks_3499819a1d8a4566ab2f2ae1aa767ff6/asks/base_funcs.py", line 8, in <module>
          from .sessions import Session
        File "/private/var/folders/7f/56kg8qsn2cz0_sbtrcvn3j5c0000gn/T/pip-install-s_mpy7ne/asks_3499819a1d8a4566ab2f2ae1aa767ff6/asks/sessions.py", line 10, in <module>
          from h11 import RemoteProtocolError
      ModuleNotFoundError: No module named 'h11'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

Let me know if you need anymore information!

Thanks!
Joe

**Comment by smurfix** [comment]
The traceback shows quite clearly that this is a problem with the `asks` package, whose `setup.py` tries to load other packages that aren't installed yet.
