### ISSUE TITLE
Can't run anymore my code, example.py also fail

### ISSUE THREAD

**Issue by arheops** [M-o-a-T/asyncari#4]
Centos 8, python39.

Give following message, any ideas?

```
python3 tests/example.py   
tg <anyio._backends._trio.TaskGroup object at 0x7f9638bf4850>
tg cancel <anyio._backends._trio.CancelScope object at 0x7f9638bf4ca0>
- <bound method CancelScope.cancel of <anyio._backends._trio.CancelScope object at 0x7f9638bf4ca0>>
DEBUG:asyncswagger11.client:Loading from http://localhost:8088/ari/api-docs/resources.json
DEBUG:asyncswagger11.client:eventWebsocket?'app=hello'
DEBUG:asyncswagger11.client:GET http://localhost:8088/ari/events({'app': 'hello'})
DEBUG:asyncari.client:ADD *
DEBUG:asyncari.client:ADD StasisStart
DEBUG:asyncari.client:DEL StasisStart
  + Exception Group Traceback (most recent call last):
  |   File "/root/fe_control/tests/example.py", line 82, in <module>
  |     anyio.run(main, backend="trio")
  |   File "/root/fe_venv/lib64/python3.9/site-packages/anyio/_core/_eventloop.py", line 66, in run
  |     return async_backend.run(func, args, {}, backend_options)
  |   File "/root/fe_venv/lib64/python3.9/site-packages/anyio/_backends/_trio.py", line 815, in run
  |     return trio.run(func, *args)
  |   File "/root/fe_venv/lib64/python3.9/site-packages/trio/_core/_run.py", line 2093, in run
  |     raise runner.main_task_outcome.error
  |   File "/root/fe_control/tests/example.py", line 76, in main
  |     print("** EVENT **", m)
  |   File "/root/fe_venv/lib64/python3.9/site-packages/async_generator/_util.py", line 53, in __aexit__
  |     await self._agen.athrow(type, value, traceback)
  |   File "/root/fe_venv/lib64/python3.9/site-packages/asyncari/__init__.py", line 45, in connect
  |     pass  # end taskgroup
  |   File "/root/fe_venv/lib64/python3.9/site-packages/anyio/_backends/_trio.py", line 160, in __aexit__
  |     return await self._nursery_manager.__aexit__(exc_type, exc_val, exc_tb)
  |   File "/root/fe_venv/lib64/python3.9/site-packages/trio/_core/_run.py", line 881, in __aexit__
  |     raise combined_error_from_nursery
  | trio.NonBaseMultiError: AttributeError("module 'anyio' has no attribute 'open_cancel_scope'")
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/root/fe_venv/lib64/python3.9/site-packages/asyncari/client.py", line 188, in _run
    |     await evt.set()
    | TypeError: object NoneType can't be used in 'await' expression
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "/root/fe_venv/lib64/python3.9/site-packages/asyncari/client.py", line 195, in _run
    |     async with anyio.open_cancel_scope(shield=True):
    | AttributeError: module 'anyio' has no attribute 'open_cancel_scope'
```

module anyio is 4.0.0

**Comment by arheops** [comment]
Works with
```
pip3 uninstall anyio
pip3 install anyio==3.7.1
```

**Comment by smurfix** [comment]
Yeah, anyio 4.0  dropped a few compatibility methods.

I'll do an update shortly.

**Comment by smurfix** [comment]
Please check 0.10.9 and holler if there are any other issues I might have overlooked.
