### ISSUE TITLE
ImportError: cannot import name 'create_semaphore' from 'anyio'

### ISSUE THREAD

**Issue by HugoCS2002** [M-o-a-T/asyncari#6]
when i try to import the module with the the following line: import asyncari
raise the error: 
Traceback (most recent call last):
  File "/opt/vosk-server/websocket/ari_script.py", line 2, in <module>
    import asyncari
  File "/usr/local/lib/python3.9/dist-packages/asyncari/__init__.py", line 11, in <module>
    from asyncswagger11.http_client import AsynchronousHttpClient, ApiKeyAuthenticator
  File "/usr/local/lib/python3.9/dist-packages/asyncswagger11/__init__.py", line 15, in <module>
    from .swagger_model import load_file, load_json, load_url, Loader
  File "/usr/local/lib/python3.9/dist-packages/asyncswagger11/swagger_model.py", line 14, in <module>
    from asyncswagger11.http_client import AsynchronousHttpClient
  File "/usr/local/lib/python3.9/dist-packages/asyncswagger11/http_client.py", line 14, in <module>
    import asks
  File "/usr/local/lib/python3.9/dist-packages/asks/__init__.py", line 5, in <module>
    from .base_funcs import *
  File "/usr/local/lib/python3.9/dist-packages/asks/base_funcs.py", line 8, in <module>
    from .sessions import Session
  File "/usr/local/lib/python3.9/dist-packages/asks/sessions.py", line 11, in <module>
    from anyio import connect_tcp, create_semaphore
ImportError: cannot import name 'create_semaphore' from 'anyio' (/usr/local/lib/python3.9/dist-packages/anyio/__init__.py)

Version package:
asyncari           0.10.9
anyio              4.1.0
Can someone help me?

**Comment by smurfix** [comment]
Wrong package. See the stack dump. The problem is with `asks`.

**Comment by HugoCS2002** [comment]
Thanks, i have also other errors but now i can import
